## Занятие 1. Обратное распространение ошибки + Numpy туториал. 

In [ ]:
! git checkout . & git pull origin main

### Подготовка среды и установка пакета 
Локально вы можете установить пакет в своей среде так, как описано в task1/README.md.

В Yandex Datasphere для корректной установке надо использовать Jupyter команду %pip, как сделано в ячейке ниже

In [47]:
from pathlib import Path
_COURSE_ROOT = Path().resolve().parent.parent
print(_COURSE_ROOT)
_TASK1_PATH = str((_COURSE_ROOT / 'task1').absolute())
print(_TASK1_PATH)

/home/jupyter/work/resources/course_cvdl
/home/jupyter/work/resources/course_cvdl/task1


In [49]:
%pip install -e {_TASK1_PATH}

Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/jupyter/work/resources/course_cvdl/task1
  Checking if build backend supports build_editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for a4_course_cvdl_t1 (pyproject.toml) ... done
  Created wheel for a4_course_cvdl_t1: filename=a4_course_cvdl_t1-0.2.0-py3-none-any.whl size=1079 sha256=3c3a41071909a7a4780e5bc1e886ae8eb637bb4a1c07a2df1c1fdc6e56ee817d
  Stored in directory: /tmp/pip-ephem-wheel-cache-dk5ykkhv/wheels/a7/a0/20/1ae21469f0f5bbdf8ddfb818fd7f65b24ace9c4ed920572a8b
Successfully built a4_course_cvdl_t1
  Attempting uninstall: a4_course_cvdl_t1
    Found existing installation: a4_course_cvdl_t1 0.2.0
    Uninstalling a4_course_cvdl_t1-0.2.0:
      Successfully uninstalled a4_course_cvdl_t1-0.2.0


### Запуск тестов пакета

In [50]:
import a4_course_cvdl_t1
from a4_course_cvdl_t1.relu import ReluLayer

Если указать конкретный модуль с тестами - будет запущен только он

Если добавить флаг `-x` - после первого падения тесты будут прерваны.

In [51]:
! pytest --pyargs a4_course_cvdl_t1.tests.test_0relu -x

============================= test session starts ==============================
platform linux -- Python 3.9.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/jupyter/work/resources/course_cvdl/classes/c01
collected 4 items

. F

=================================== FAILURES ===================================
_______________________ TestLayer.test_init[test_data0] ________________________

self = <a4_course_cvdl_t1.tests.base.TestLayer object at 0x7f8605da53d0>
test_data = {'meta': {'description': 'The only ReLU test.', 'layer_kwargs': {}}, 'values': {'input': [[[[0.3445909917354584, -0.44...36354065], [0.320019006729126, 0.7765920162200928, 0.8497490286827087, 0.796563982963562, 0.9298689961433411]]]], ...}}
test_layer_cls = <class 'a4_course_cvdl_t1.relu.ReluLayer'>

    def test_init(self, test_data, test_layer_cls):
        values = test_data['values']
        meta = test_data['meta']
        layer_kwargs = meta['layer_kwargs']
    
        # check layer creation
        try:
>        

Exception: Process exited with code 1

In [52]:
import numpy as np
from a4_course_cvdl_t1.relu import ReluLayer
print(help(ReluLayer))

Help on class ReluLayer in module a4_course_cvdl_t1.relu:

class ReluLayer(a4_course_cvdl_t1.base.BaseLayer)
 |  Слой, выполняющий Relu активацию y = max(x, 0).
 |  Не имеет параметров.
 |  
 |  Method resolution order:
 |      ReluLayer
 |      a4_course_cvdl_t1.base.BaseLayer
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  backward(self, output_grad: numpy.ndarray) -> numpy.ndarray
 |      Принимат dL/dy, возвращает dL/dx.
 |  
 |  forward(self, input: numpy.ndarray) -> numpy.ndarray
 |      Принимает x, возвращает y(x)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from a4_course_cvdl_t1.base.BaseLayer:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  -------------------------------------------------

### Исправляем ReluLayer.1
Задача: дописать ReluLayer.\_\_init\_\_, .forward()

### Создание тензоров

In [53]:
a = np.random.rand(2, 3, 4) - 0.5
b = np.zeros(a.shape)
print(a) 
print(b)

[[[ 0.09391292  0.35734647 -0.3503454  -0.08923428]
  [-0.46561049  0.11486326  0.24514212  0.22217756]
  [ 0.21713041  0.18565045 -0.296113    0.44627214]]

 [[-0.47745257  0.40048562 -0.25353957  0.17430979]
  [-0.42688944 -0.48217679 -0.25995528  0.33906299]
  [ 0.02201373 -0.29682538  0.00854723 -0.2632649 ]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### Поиск максимума

In [54]:
np.max(a)

0.4462721386847839

In [55]:
np.maximum(a, b)

array([[[0.09391292, 0.35734647, 0.        , 0.        ],
        [0.        , 0.11486326, 0.24514212, 0.22217756],
        [0.21713041, 0.18565045, 0.        , 0.44627214]],

       [[0.        , 0.40048562, 0.        , 0.17430979],
        [0.        , 0.        , 0.        , 0.33906299],
        [0.02201373, 0.        , 0.00854723, 0.        ]]])

In [56]:
np.argmax(a)

11

Argmax возвращает "плоский" индекс, его нельзя использовать напрямую для индексации многомерного массива - получится
**IndexError**

In [57]:
print(a.flatten()[np.argmax(a)])
print('---IndexError----')
a[np.argmax(a)]

0.4462721386847839
---IndexError----


IndexError: index 11 is out of bounds for axis 0 with size 2

"Плоский" индекс можно раскрутитьв N-мерный индекс, и использовать его для индексации

In [ ]:
idx_nd = np.unravel_index(np.argmax(a), a.shape)
print(idx_nd)
a[idx_nd]

### Поэлементные операции

In [58]:
a * b

array([[[ 0.,  0., -0., -0.],
        [-0.,  0.,  0.,  0.],
        [ 0.,  0., -0.,  0.]],

       [[-0.,  0., -0.,  0.],
        [-0., -0., -0.,  0.],
        [ 0., -0.,  0., -0.]]])

In [59]:
a + b

array([[[ 0.09391292,  0.35734647, -0.3503454 , -0.08923428],
        [-0.46561049,  0.11486326,  0.24514212,  0.22217756],
        [ 0.21713041,  0.18565045, -0.296113  ,  0.44627214]],

       [[-0.47745257,  0.40048562, -0.25353957,  0.17430979],
        [-0.42688944, -0.48217679, -0.25995528,  0.33906299],
        [ 0.02201373, -0.29682538,  0.00854723, -0.2632649 ]]])

### Срезы

In [60]:
print("a             \t", a.shape)
print("a[0]          \t", a[0].shape)
print("a[:, 0]       \t", a[:, 0].shape)
print("a[:, 0, 1:2]  \t", a[:, 0, 0:2].shape)
print("a[:, [0], 1:2]\t", a[:, [0], 0:2].shape)
print("a[:, None]    \t", a[:, None].shape)

a             	 (2, 3, 4)
a[0]          	 (3, 4)
a[:, 0]       	 (2, 4)
a[:, 0, 1:2]  	 (2, 2)
a[:, [0], 1:2]	 (2, 1, 2)
a[:, None]    	 (2, 1, 3, 4)


### Индексация
Булевая индексация: индекс имеет форму тензора со значениями True и False

In [61]:
idx = a > 0
print(a.shape, idx.shape, idx.dtype)
idx

(2, 3, 4) (2, 3, 4) bool


array([[[ True,  True, False, False],
        [False,  True,  True,  True],
        [ True,  True, False,  True]],

       [[False,  True, False,  True],
        [False, False, False,  True],
        [ True, False,  True, False]]])

Результат индексации - плоский массив

In [62]:
a[idx].shape

(13,)

In [63]:
a[a == np.max(a)]

array([0.44627214])

Индексация "координатами": индекс - массивы N-мерных координат элементов

In [64]:
# Создадим пробный тензор для индексации
c = np.arange(
    np.prod(a.shape)
).reshape(a.shape)
print(c.shape)
c

(2, 3, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [65]:
# Каждый столбец - индексирует один элемент
# Результат - плоский список
c[
    [0,  1,  0,  0,  0,  0],
    [1, -1,  2, -1, -1, -1],
    [3,  2,  1,  0,  0,  0]
]

array([ 7, 22,  9,  8,  8,  8])

In [66]:
# Если индексы - не плоские, то и результат не плоский
c[
    [[0,  1,  0],[  0,  0,  0]],
    [[1, -1,  2],[ -1, -1, -1]],
    [[3,  2,  1],[  0, 0,   0]],
]

array([[ 7, 22,  9],
       [ 8,  8,  8]])

### Исправляем ReluLayer.2
Задача: дописать ReluLayer.backward()

In [67]:
! pytest --pyargs a4_course_cvdl_t1.tests.test_0relu -x

============================= test session starts ==============================
platform linux -- Python 3.9.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/jupyter/work/resources/course_cvdl/classes/c01
collected 4 items

. F

=================================== FAILURES ===================================
_______________________ TestLayer.test_init[test_data0] ________________________

self = <a4_course_cvdl_t1.tests.base.TestLayer object at 0x7f3a8351f9d0>
test_data = {'meta': {'description': 'The only ReLU test.', 'layer_kwargs': {}}, 'values': {'input': [[[[0.3445909917354584, -0.44...36354065], [0.320019006729126, 0.7765920162200928, 0.8497490286827087, 0.796563982963562, 0.9298689961433411]]]], ...}}
test_layer_cls = <class 'a4_course_cvdl_t1.relu.ReluLayer'>

    def test_init(self, test_data, test_layer_cls):
        values = test_data['values']
        meta = test_data['meta']
        layer_kwargs = meta['layer_kwargs']
    
        # check layer creation
        try:
>        

Exception: Process exited with code 1

Исправляем в форке и проверяем баллы после теста

### Broadcasting

In [68]:
# Пусть у нас есть куча 2D точек
a = np.array([
    [0, 1],
    [2, 3],
    [4, 5],
    [6, 7]
])

# И мы хотим их все "сдвинуть" на 2D вектор-константу
b = np.array([10, 20])

print(a.shape, b.shape)

(4, 2) (2,)


In [69]:
# Работает!
a + b

array([[10, 21],
       [12, 23],
       [14, 25],
       [16, 27]])

In [70]:
# Попробуем теперь каждой точке добавить разный сдвиг
b = np.array([10, 20, 30, 40])
print(a.shape, b.shape)
print("Broadcast error")
print("---------------")
a + b
# не работает, т.к. форма не п

(4, 2) (4,)
Broadcast error
---------------


ValueError: operands could not be broadcast together with shapes (4,2) (4,) 

In [82]:
# Приводим тензоры явно к форме для бродкаста
print(a.shape, b[:, None].shape)

a * b[:, None]

(2, 3, 4) (3, 1)


array([[[  0.  ,   3.33,   6.66,   9.99],
        [ 29.32,  36.65,  43.98,  51.31],
        [ 90.64, 101.97, 113.3 , 124.63]],

       [[ 39.96,  43.29,  46.62,  49.95],
        [117.28, 124.61, 131.94, 139.27],
        [226.6 , 237.93, 249.26, 260.59]]])

In [83]:
a = np.array([
    [0, 1],
    [1, 0],
    [1, 1]
])
b = np.array([
    [10, 20],
    [30, 40],
    [50, 60],
    [70, 80]
])
c = a[None] * b[:, None]
print("c[i, j, k] = a[1, i, k] * b[j, 1, k]")
print("------------------------------")
print(a.shape, b.shape, c.shape)

print(c)

c[i, j, k] = a[1, i, k] * b[j, 1, k]
------------------------------
(3, 2) (4, 2) (4, 3, 2)
[[[ 0 20]
  [10  0]
  [10 20]]

 [[ 0 40]
  [30  0]
  [30 40]]

 [[ 0 60]
  [50  0]
  [50 60]]

 [[ 0 80]
  [70  0]
  [70 80]]]


### Tensordot

In [84]:
help(np.tensordot)

Help on _ArrayFunctionDispatcher in module numpy:

tensordot(a, b, axes=2)
    Compute tensor dot product along specified axes.
    
    Given two tensors, `a` and `b`, and an array_like object containing
    two array_like objects, ``(a_axes, b_axes)``, sum the products of
    `a`'s and `b`'s elements (components) over the axes specified by
    ``a_axes`` and ``b_axes``. The third argument can be a single non-negative
    integer_like scalar, ``N``; if it is such, then the last ``N`` dimensions
    of `a` and the first ``N`` dimensions of `b` are summed over.
    
    Parameters
    ----------
    a, b : array_like
        Tensors to "dot".
    
    axes : int or (2,) array_like
        * integer_like
          If an int N, sum over the last N axes of `a` and the first N axes
          of `b` in order. The sizes of the corresponding axes must match.
        * (2,) array_like
          Or, a list of axes to be summed over, first sequence applying to `a`,
          second to `b`. Both e

In [85]:
a = np.array([
    [0.5, -0.5],
    [-0.5, 0.5],
    [1, 0.]
])
b = np.array([10, 1])
print("c[i, k] = Sum(a[i, j] * b[j, k]")
print('-------------------------------')
print(a.shape, b.shape)
a @ b

c[i, k] = Sum(a[i, j] * b[j, k]
-------------------------------
(3, 2) (2,)


array([ 4.5, -4.5, 10. ])

In [86]:
np.tensordot(
    a, b,
    axes=[1, 0]
)

array([ 4.5, -4.5, 10. ])

Многомерный tensordot

In [87]:
a = np.arange(2* 3 *4).reshape((2, 3 ,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [88]:
b = np.arange(4 * 2).reshape((4, 2)) % 2
b

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])

In [89]:
np.tensordot(
    a, b,
    axes=[
        [-1, 0],
        [0, 1]
    ]
)

array([54, 70, 86])

### View vs Copy

In [90]:
a = np.arange(2 * 3 * 4).reshape((2, 3 , 4)).astype(float)
b = a[1:, 1:, 1:]
b += 0.33
print(b)
print("---------")
print(a)

[[[17.33 18.33 19.33]
  [21.33 22.33 23.33]]]
---------
[[[ 0.    1.    2.    3.  ]
  [ 4.    5.    6.    7.  ]
  [ 8.    9.   10.   11.  ]]

 [[12.   13.   14.   15.  ]
  [16.   17.33 18.33 19.33]
  [20.   21.33 22.33 23.33]]]


In [91]:
a = np.arange(2 * 3 * 4).reshape((2, 3 , 4)).astype(float)
b = a[1, 1, 1]
b += 0.33
print(b)
print("---------")
print(a)

17.33
---------
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


In [92]:
a = np.arange(2 * 3 * 4).reshape((2, 3 , 4)).astype(float)
b = a[None, 1:, 1:, 1:]
b += 0.33
print(b)
print("---------")
print(a)

[[[[17.33 18.33 19.33]
   [21.33 22.33 23.33]]]]
---------
[[[ 0.    1.    2.    3.  ]
  [ 4.    5.    6.    7.  ]
  [ 8.    9.   10.   11.  ]]

 [[12.   13.   14.   15.  ]
  [16.   17.33 18.33 19.33]
  [20.   21.33 22.33 23.33]]]


In [93]:
a = np.arange(2 * 3 * 4).reshape((2, 3 , 4)).astype(float)
a[[0,0,0],[0, 1, 2], [-1, -1, -1]] += 0.33
print(a)

[[[ 0.    1.    2.    3.33]
  [ 4.    5.    6.    7.33]
  [ 8.    9.   10.   11.33]]

 [[12.   13.   14.   15.  ]
  [16.   17.   18.   19.  ]
  [20.   21.   22.   23.  ]]]


In [81]:
a = np.arange(2 * 3 * 4).reshape((2, 3 , 4)).astype(float)
b = a[[0,0,0],[0, 1, 2], [-1, -1, -1]] 
b += 0.33
print(a)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
